src/Entity/CategoriesTable.php
<?php

namespace App\Entity;

use App\Repository\CategoriesTableRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoriesTableRepository::class)
 */
class CategoriesTable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tag;

    /**
     * @ORM\OneToMany(targetEntity=Todo::class, mappedBy="TagName")
     */
    private $todos;

    public function __construct()
    {
        $this->todos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTag(): ?string
    {
        return $this->Tag;
    }

    public function setTag(string $Tag): self
    {
        $this->Tag = $Tag;

        return $this;
    }

    /**
     * @return Collection<int, Todo>
     */
    public function getTodos(): Collection
    {
        return $this->todos;
    }

    public function addTodo(Todo $todo): self
    {
        if (!$this->todos->contains($todo)) {
            $this->todos[] = $todo;
            $todo->setTagName($this);
        }

        return $this;
    }

    public function removeTodo(Todo $todo): self
    {
        if ($this->todos->removeElement($todo)) {
            // set the owning side to null (unless already changed)
            if ($todo->getTagName() === $this) {
                $todo->setTagName(null);
            }
        }

        return $this;
    }
}

src/Entity/Todo.php
<?php

namespace App\Entity;

use App\Repository\TodoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TodoRepository::class)
 */
class Todo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $priority;

    /**
     * @ORM\Column(type="date")
     */
    private $due_date;

    /**
     * @ORM\ManyToOne(targetEntity=CategoriesTable::class, inversedBy="todos")
     */
    private $TagName;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getPriority(): ?string
    {
        return $this->priority;
    }

    public function setPriority(string $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getDueDate(): ?\DateTimeInterface
    {
        return $this->due_date;
    }

    public function setDueDate(\DateTimeInterface $due_date): self
    {
        $this->due_date = $due_date;

        return $this;
    }

    public function getTagName(): ?CategoriesTable
    {
        return $this->TagName;
    }

    public function setTagName(?CategoriesTable $TagName): self
    {
        $this->TagName = $TagName;

        return $this;
    }

}

src/Form/TodoType.php
<?php

namespace App\Form;

use App\Entity\Todo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TodoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class)
            ->add('category', TextType::class)
            ->add('description', TextareaType::class)
            ->add('priority', ChoiceType::class, [
                'choices' => [
                    '1' => "1",
                    '2' => "2",
                    '3' => "3",
                ],
            ])
            ->add('due_date', DateType::class, ['widget' => 'single_text']);
    }


    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Todo::class,
        ]);

    }
}

src/Controller/TodoController.php
<?php

namespace App\Controller;

use App\Entity\Todo;
use App\Form\TodoType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TodoController extends AbstractController
{
    /**
     * @Route("/todo", name="todo_list")
     */
    public function listAction()
    {
        $todos = $this->getDoctrine()
            ->getRepository(Todo::class)
            ->findAll();
        return $this->render('todo/index.html.twig', [
            'todos' => $todos
        ]);
    }

    /**
     * @Route("/todo/details/{id}", name="todo_details")
     */
    public
    function detailsAction($id)
    {
        $todos = $this->getDoctrine()
            ->getRepository(Todo::class)
            ->find($id);

        return $this->render('todo/details.html.twig', [
            'todos' => $todos
        ]);
    }
    /**
     * @Route("/todo/delete/{id}", name="todo_delete")
     */
    public function deleteAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $todo = $em->getRepository(Todo::class)->find($id);
        $em->remove($todo);
        $em->flush();

        $this->addFlash(
            'error',
            'Todo deleted'
        );

        return $this->redirectToRoute('todo_list');
    }

    /**
     * @Route("/todo/create", name="todo_create", methods={"GET","POST"})
     */
    public function createAction(Request $request)
    {
        $todo = new Todo();
        $form = $this->createForm(TodoType::class, $todo);

        if ($this->saveChanges($form, $request, $todo)) {
            $this->addFlash(
                'notice',
                'Todo Added'
            );

            return $this->redirectToRoute('todo_list');
        }

        return $this->render('todo/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    public function saveChanges($form, $request, $todo)
    {
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $todo->setName($request->request->get('todo')['name']);
            $todo->setCategory($request->request->get('todo')['category']);
            $todo->setDescription($request->request->get('todo')['description']);
            $todo->setPriority($request->request->get('todo')['priority']);
            $todo->setDueDate(\DateTime::createFromFormat('Y-m-d', $request->request->get('todo')['due_date']));
            $em = $this->getDoctrine()->getManager();
            $em->persist($todo);
            $em->flush();

            return true;
        }
        return false;
    }

    /**
     * @Route("/todo/edit/{id}", name="todo_edit")
     */
    public function editAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $todo = $em->getRepository(Todo::class)->find($id);

        $form = $this->createForm(TodoType::class, $todo);

        if ($this->saveChanges($form, $request, $todo)) {
            $this->addFlash(
                'notice',
                'Todo Edited'
            );
            return $this->redirectToRoute('todo_list');
        }

        return $this->render('todo/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }









        }

templates/base.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/starter-template/">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    {% block stylesheets %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ path('todo_list') }}">Todo List Symfony</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{{ path('todo_list') }}">Home</a></li>
                <li><a href="{{ path('todo_create') }}">Add Todo</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            {% for flash_message in app.session.flashBag.get('notice') %}
                <div class="alert alert-success">{{ flash_message }}</div>
            {% endfor %}
            {% for flash_message in app.session.flashBag.get('error') %}
                <div class="alert alert-danger">{{ flash_message }}</div>
            {% endfor %}
            {% block body %}{% endblock %}
        </div>
    </div>
</div>
</div><!-- /.container -->

{% block javascripts %}{% endblock %}

</body>
</html>

templates/todo/create.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {{ form_start(form) }}
<div class="form-group">
    <label for="name">Name:</label>
    {{ form_widget(form.name,{
        'attr':{
            'class':'form-control',
            'placeholder': 'Task name'
        }
    }) }}
    <div class="invalid-feedback">
        {{ form_errors(form.name) }}
    </div>
</div>
<div class="form-group">
    <label for="category">Category:</label>
    {{ form_widget(form.category,{
        'attr':{
            'class':'form-control',
            'placeholder': 'Category name'
        }
    }) }}
</div>
<div class="form-group">
    <label for="description">Description:</label>
    {{ form_widget(form.description,{
        'attr':{
            'class':'form-control',
            'placeholder': 'Description'
        }
    }) }}
</div>
<div class="form-group">
    <label for="priority">Priority:</label>
    {{ form_widget(form.priority,{
        'attr':{
            'class':'form-control'
        }
    }) }}
</div>
<div class="form-group">
    <label for="due_date">Due Date</label>
    {{ form_widget(form.due_date,{
        'attr':{
            'class':'form-control'
        }
    }) }}
</div>
<input type="submit" name="create_todo" value="Create" class="btn btn-primary"/>
    {{ form_end(form) }}
{% endblock %}

templates/todo/details.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <a href="{{ path('todo_list') }}" class="btn btn-default">Back to Todo List</a>
    <hr/>
    <h2 class="page-header">{{ todos.name }}</h2>
    <ul class="list-group">
        <li class="list-group-item">Category: {{ todos.category }}</li>
        <li class="list-group-item">Priority: {{ todos.priority }}</li>
        <li class="list-group-item">Due: <strong>{{ todos.dueDate|date('F j,Y, g:i a') }}</strong></li>
    </ul>
    <p>{{ todos.description }}</p>
{% endblock %}

templates/todo/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form_start(form) }}
<div class="form-group">
    <label for="name">Name:</label>
    {{ form_widget(form.name,{
        'attr':{
            'class':'form-control',
            'placeholder': 'Task name'
        }
    }) }}
</div>
<div class="form-group">
    <label for="category">Category:</label>
    {{ form_widget(form.category,{
        'attr':{
            'class':'form-control',
            'placeholder': 'Category name'
        }
    }) }}
</div>
<div class="form-group">
    <label for="description">Description:</label>
    {{ form_widget(form.description,{
        'attr':{
            'class':'form-control',
            'placeholder': 'Description'
        }
    }) }}
</div>
<div class="form-group">
    <label for="priority">Priority:</label>
    {{ form_widget(form.priority,{
        'attr':{
            'class':'form-control'
        }
    }) }}
</div>
    <div class="form-group">
        <label for="due_date">Due Date</label>
        {{ form_widget(form.due_date,{
            'attr':{
                'class':'form-control'
            }
        }) }}
    </div>
    <input type="submit" name="edit_todo" value="Edit" class="btn btn-primary"/>
    {{ form_end(form) }}
{% endblock %}

templates/todo/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="bs-example" data-example-id="striped-table">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Todo</th>
            <th>Due date</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for todo in todos %}
        <tr>
            <th scope="row">{{ todo.id }}</th>
            <td>{{ todo.name }}</td>
            <td>{{ todo.dueDate|date('F j,Y, g:i a') }}</td>
            <td>
                {#<a href="{{ path('todo_details', {'id': todo.id}) }} " class='btn btn-success'>View</a>#}
                {#<a href="{{ path('todo_edit', {'id': todo.id}) }}" class='btn btn-default'>Edit</a>#}
                {#<a href="{{ path('todo_delete', {'id': todo.id}) }}" class='btn btn-danger'>Delete</a>#}
                <a href="{{ path('todo_details', {'id': todo.id}) }} " class='btn btn-success'>View</a>
                <a href="{{ path('todo_edit', {'id': todo.id}) }}" class='btn btn-default'>Edit</a>
                <a href="{{ path('todo_delete', {'id': todo.id}) }}" class='btn btn-danger'>Delete</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}